#!/usr/bin/env python

# getopt

# getopt is a C library function to parse command-line options

import sys, getopt

def main(argv):
    inputfile = ''
    outputfile = ''
    try:
        opts, args = getopt.getopt(argv, "hi:o:", ["ifile=", "ofile="])
    except getopt.GetoptError:
        print 'test.py -i <inputfile> -o <outputfile>'
        sys.exit(2)
    for opt, arg in opts:
        if opt == '-h':
            print 'test.py -i <inputfile> -o <outputfile>'
            sys.exit()
        elif opt in ("-i", "--ifile"):
            inputfile = arg
        elif opt in ("-o", "--ofile"):
            outputfile = arg
    print 'Input file is: ', inputfile
    print 'Output file is: ', outputfile


if __name__ == "__main__":
    main(sys.argv[1:])


# short flags
# long flags
# i:  and o: must be followed by an argument


#Source: http://www.tutorialspoint.com/python/python_command_line_arguments.htm
