# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "kenny/salty-centos-6.5"
  config.vm.synced_folder ".", "/vagrant"
  
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "256"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--usb", "off"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
  end

  config.vm.define "master", primary: true do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.50.5"
    master.vm.synced_folder "salt/states", "/srv/salt"
    master.vm.provision "shell", inline: "service iptables stop"
    master.vm.provision :salt do |salt|
      salt.install_master = true
      salt.master_config = "salt/master"
      salt.master_key = "salt/keys/master.pem"
      salt.master_pub = "salt/keys/master.pub"
      salt.seed_master = {minion1: "salt/keys/minion1.pub",
                          minion2: "salt/keys/minion2.pub",
                          minion3: "salt/keys/minion3.pub",
                          minion4: "salt/keys/minion4.pub"}
      salt.run_highstate = false
    end
  end

  (1..4).each do |i|
    config.vm.define "minion#{i}" do |node|
      node.vm.hostname = "minion#{i}"
      node.vm.network "private_network", ip: "192.168.50.#{i+5}"
      node.vm.provision "shell", inline: "echo 'minion#{i}' > /etc/salt/minion_id"
      node.vm.provision :salt do |salt|
        salt.minion_config = "salt/minion"
        salt.minion_key = "salt/keys/minion#{i}.pem"
        salt.minion_pub = "salt/keys/minion#{i}.pub"
        salt.run_highstate = true
      end
    end
  end

end
